// src/utils/FileUtil.js
const os = require('os');
const path = require('path');
const fs = require('fs');
const https = require('https');
const crypto = require('crypto');

// --- Encryption Constants (Simplistic for demonstration. A real app needs robust key management.) ---
const ENCRYPTION_ALGORITHM = 'aes-256-cbc';
// This key should be derived securely in a production environment
const ENCRYPTION_KEY = Buffer.from('a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6'); 
const IV_LENGTH = 16; // 16 bytes for AES-256-CBC

/**
 * @description Gets the base path for application data storage based on the OS.
 * Follows the BridgeWebPopper specification (%APPDATA% on Windows).
 * @returns {string} The platform-specific application data directory path.
 */
function getAppDataPath() {
    switch (process.platform) {
        case 'win32':
            // Use APPDATA for roaming data on Windows
            return process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
        case 'darwin':
            // Use Application Support on macOS
            return path.join(os.homedir(), 'Library', 'Application Support');
        default:
            // Use local share for Linux/other
            return path.join(os.homedir(), '.local', 'share');
    }
}

/**
 * @description Encrypts a plain text string (e.g., password) using AES-256-CBC.
 * @param {string} text - The plain text string to encrypt.
 * @returns {string} The base64-encoded encrypted string, including the IV.
 */
function encrypt(text) {
    if (!text) return '';
    const iv = crypto.randomBytes(IV_LENGTH);
    const cipher = crypto.createCipheriv(ENCRYPTION_ALGORITHM, ENCRYPTION_KEY, iv);
    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    // Prepend the IV to the encrypted text for decryption
    return iv.toString('hex') + ':' + encrypted;
}

/**
 * @description Decrypts an encrypted string generated by the encrypt function.
 * @param {string} encryptedText - The base64-encoded encrypted string with IV.
 * @returns {string} The decrypted plain text string.
 */
function decrypt(encryptedText) {
    if (!encryptedText) return '';
    try {
        const parts = encryptedText.split(':');
        const iv = Buffer.from(parts.shift(), 'hex');
        const encryptedData = parts.join(':');
        const decipher = crypto.createDecipheriv(ENCRYPTION_ALGORITHM, ENCRYPTION_KEY, iv);
        let decrypted = decipher.update(encryptedData, 'hex', 'utf8');
        decrypted += decipher.final('utf8');
        return decrypted;
    } catch (error) {
        console.error("Decryption failed:", error);
        return ''; // Return empty string on failure
    }
}

/**
 * @description Downloads a file from a URL and saves it to a local path.
 * Note: Only supports HTTPS for simplicity based on the target API.
 * @param {string} url - The full URL of the file to download.
 * @param {string} localPath - The full path where the file should be saved.
 * @returns {Promise<void>} A promise that resolves when the file is successfully downloaded.
 */
function downloadFile(url, localPath) {
    return new Promise((resolve, reject) => {
        // Ensure the directory exists
        const dir = path.dirname(localPath);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }

        const file = fs.createWriteStream(localPath);
        https.get(url, (response) => {
            if (response.statusCode !== 200) {
                file.close();
                fs.unlink(localPath, () => {}); // Delete the incomplete file
                return reject(new Error(`Failed to download file. Status Code: ${response.statusCode}`));
            }

            response.pipe(file);

            file.on('finish', () => {
                file.close(resolve);
            });
        }).on('error', (err) => {
            fs.unlink(localPath, () => {}); // Delete the incomplete file on error
            reject(err);
        });
    });
}

module.exports = {
    getAppDataPath,
    encrypt,
    decrypt,
    downloadFile
};